### ISSUE TITLE
bundle with kotlin

### ISSUE THREAD

**Issue by j209** [karl-run/spring-boot-kotlin-cra#2]
Hi
What about bundling spring boot with [Create React Kotlin App](https://github.com/JetBrains/create-react-kotlin-app) to have only kotlin in front end and backend?

**Comment by karl-run** [comment]
That would be interesting indeed, and actually quite simple to do. The only coupling between the server and the web projects are that there needs to be a "build" script in package.json, and that the output of that build ends up in `web/dist`. So simply replacing the content of the web folder with CRKA would work. :smile: 

I'm maintaining this more as a quickstart for the setup for hosting the built single-page-app using Spring Boot, so I'm keeping it as "pure" as possible. But feel free to fork and play around!
