### ISSUE TITLE
How to use with newer version Kotlin

### ISSUE THREAD

**Issue by TendezaDev** [karl-run/spring-boot-kotlin-cra#28]
How do I sucessfully upgrade the versions in this project. (Doesn't work since it contains old versions, I'm new to Kotlin/Gradle)

**Comment by karl-run** [comment]
Hi. Sorry for the slow response. It's probably best to avoid this template as it's a bit outdated. You could probably extract some of the concepts from this, but I'd start from scratch from the official spring boot starter: https://start.spring.io/.
